# Generated by Django 5.2 on 2025-04-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0002_school_special_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolAdminProfile',
        ),
    ]
