# Generated by Django 5.2 on 2025-04-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0003_delete_schooladminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_code', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('tsc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_primary_admin', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='exam_portal.school')),
            ],
        ),
    ]
