# Generated by Django 5.2 on 2025-05-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0004_schooladminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='special_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
