# Generated by Django 5.2 on 2025-05-01 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0005_alter_school_special_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
