# Generated by Django 5.2 on 2025-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0006_alter_examresult_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='overallresult',
            name='average_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='overallresult',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
