# Generated by Django 5.2 on 2025-05-01 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_portal', '0007_alter_examresult_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaperArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('MAIN', 'Main Exam'), ('SUPP', 'Supplementary'), ('MOCK', 'Mock Exam'), ('SPEC', 'Special Paper')], default='MAIN', max_length=4)),
                ('paper_code', models.CharField(help_text='Unique code for this paper', max_length=20)),
                ('paper_title', models.CharField(max_length=200)),
                ('paper_file', models.FileField(upload_to='exam_papers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_confidential', models.BooleanField(default=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_papers', to=settings.AUTH_USER_MODEL)),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_portal.examyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_portal.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exam Paper Archives',
                'ordering': ['-exam_year__year', 'subject__name'],
                'unique_together': {('exam_year', 'subject', 'paper_code')},
            },
        ),
        migrations.CreateModel(
            name='PaperReleaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_portal.exampaperarchive')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paper Release Schedules',
            },
        ),
    ]
